export const MoonsetConstants = {
    TAG_MOONSET_ID: 'moonset:id',
    TAG_MOONSET_TYPE: 'moonset:type',
    TAG_MOONSET_TYPE_EMR: 'EMR',
    TAG_MOONSET_TYPE_SF: 'StepFunction',
    TAG_MOONSET_TYPE_CF: 'CloudFomration',
    TAG_MOONSET_TYPE_SERVICE_SECURITY_GROUP: 'ServiceSecurityGroup',
    TAG_MOONSET_TYPE_LOG_S3_BUCEKT: 'S3LogBucket',
    TAG_MOONSET_TYPE_VPC: 'Vpc',
    TAG_MOONSET_TYPE_VPC_SERCURITY_GROUP: 'VpcDefaultSecurityGroup',
    TAG_MOONSET_TYPE_EMR_EC2_ROLE: 'EmrEc2Role',
    TAG_MOONSET_TYPE_EMR_ROLE: 'EmrRole',
    CDK_APP: 'MoonsetApp',
    INFRA_STACK: 'MoonsetInfraStack',
    JOB_STACK: 'MoonsetJobStack',
    SF_STACK: 'MoonsetStepFunctionStack',
    SF: 'MoonsetStepFunction',
    VPC: 'MoonsetVpc',
    VPC_SG: 'MoonsetVpcSecurityGroup',
    EMR_EC2_ROLE: 'MoonsetEmrEc2Role',
    EMR_EC2_PROFILE: 'MoonsetEmrEc2Profile',
    EMR_ROLE: 'MoonsetEmrRole',
    SCRIPT_RUNNER: 's3://elasticmapreduce/libs/script-runner/script-runner.jar',
    BUILD_TMP_DIR: './build/',
    CDK_OUT_DIR: 'cdk.out/',
    MOONSET_PROPS: 'moonset.props'
};
